### ISSUE TITLE
Why UserDto and MessageDto?

### ISSUE THREAD

**Issue by rwinch** [rwinch/spring-security-4.1-and-beyond#10]

**Comment by jgrandja** [comment]
There was an issue when I originally tested returning the Message Entity where some of the properties were not being written to the response, for example the id property. And there wasn't a @JsonIgnore on those properties either. I suspect it might have been related to data-rest but not entirely sure. Either way, I didn't want to spend too much effort on it at that time so I created the Dto's as a workaround.
Good news is that the originally issue is not happening anymore so removing the Dto's
