### ISSUE TITLE
Make the default page load the inbox

### ISSUE THREAD

**Issue by rwinch** [rwinch/spring-security-4.1-and-beyond#17]
Right now the default page doesn't load anything. See [http://localhost:8080/](http://localhost:8080/)

![image](https://cloud.githubusercontent.com/assets/362503/17303579/f30ddb70-57e6-11e6-873c-9d6a29e1ff9a.png)

We should load the inbox instead of a blank page.

**Comment by jgrandja** [comment]
This is fixed by #8
