### ISSUE TITLE
Use Spring Security naming schemes

### ISSUE THREAD

**Issue by rwinch** [rwinch/spring-security-4.1-and-beyond#7]
Rather than "/custom-login" and "/login-error" use "/login" and "/login?error" to:
- reduce configuration 
- make more like a real application (no real app will have custom- in the URL)

**NOTE** See https://github.com/rwinch/spring-security-4.1-and-beyond/issues/7

cc @jgrandja

**Comment by jgrandja** [comment]
Changed to /login and /login?error
