### ISSUE TITLE
Custom Log In should not perform redirect

### ISSUE THREAD

**Issue by rwinch** [rwinch/spring-security-4.1-and-beyond#8]
We should allow access to the home page and deny access to any rest resources. The processing of the rest resource should trigger a 401 which should trigger the authentication dialog to pop up. This demonstrates the content negotiation within Spring Security

This is similar to https://github.com/rwinch/spring-state-securing-restful-apis/blob/master/messages-session/src/main/java/sample/config/SecurityConfig.java#L28

Also see https://youtu.be/Z1DfpxQ84as?t=21m45s

**Comment by jgrandja** [comment]
Home Page is allowed access by default. When accessing a protected resource Angular will handle the 401 and display the login page.
After successful login, the inbox will be displayed.
